<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>30&nbsp; 30.  Intro to SQL Select (assumes some knowledge of dplyr) – Data Management With R (latest version)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./sql0010-introToSql-v023.html" rel="next">
<link href="./sql0006-introToDatabases-v023.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-dcbfc57d77cecfb36a223989b6e6cd2b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<script src="yrstuff-v001.js"></script>


<link rel="stylesheet" href="yrStyles-main-v001.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./sql0014-theBooksDatabase-v001.html">Relational databases and SQL</a></li><li class="breadcrumb-item"><a href="./0500400-sqlSelectIntro-v003.html"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title"><yrchapternumber>30. </yrchapternumber> Intro to SQL Select ***(assumes some knowledge of dplyr)***</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Management With R (latest version)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><yrchapternumber></yrchapternumber> Intro</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Some computer basics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro00100-operatingSystems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><yrchapternumber>1. </yrchapternumber> What is an "operating system"</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro00120-files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><yrchapternumber>2. </yrchapternumber> Working with files</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Intro to Bash</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000006-bash-externalResources-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><yrchapternumber>3. </yrchapternumber> Intro to Bash - external resources</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000011-WhatIsACli-v010.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><yrchapternumber>4. </yrchapternumber> Command Line Interfaces (CLI)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000013-HowToRunTheBashShellCli-v011.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title"><yrchapternumber>5. </yrchapternumber> How to run the Bash Shell</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000025-introToBash-v007.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title"><yrchapternumber>6. </yrchapternumber> Working with the Bash Shell.</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Into to Coding With AI</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ai-000100-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><yrchapternumber>7. </yrchapternumber> AI in Everyday Use</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./aiCoding00100-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title"><yrchapternumber>8. </yrchapternumber> Coding with AI - an overview</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro00130-chromeExtensions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title"><yrchapternumber>9. </yrchapternumber> Using AI to code a Chrome Extensions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Intro to R packages</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000022-InstallingRPackages-v003.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title"><yrchapternumber>10. </yrchapternumber> Intro to R packages</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Intro to Quarto</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000017-introToQuarto-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title"><yrchapternumber>11. </yrchapternumber> Intro to Quarto</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Intro to tidyverse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0400050-whatIsTidyverse-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title"><yrchapternumber>12. </yrchapternumber> What is the "tidyverse"</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0400050-tibbles-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title"><yrchapternumber>13. </yrchapternumber> tibbles and tribbles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0400100-usingPipes-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title"><yrchapternumber>14. </yrchapternumber> Using pipes, i.e. %&gt;% and |&gt;</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0400200-stringr-tutorials-v003.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title"><yrchapternumber>15. </yrchapternumber> stringr tutorial</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Working with files</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000055-workingWithFiles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title"><yrchapternumber>16. </yrchapternumber> Working with files</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">JSON data and APIs</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000075-whatIsJsonData.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title"><yrchapternumber>17. </yrchapternumber> Intro to JSON data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000080-editingAndValidatingJsonFiles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title"><yrchapternumber>18. </yrchapternumber> Creating, editing and validating JSON files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000085-jsonDataTypes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title"><yrchapternumber>19. </yrchapternumber> DATA TYPES IN JSON</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000090-usingJsonInR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title"><yrchapternumber>20. </yrchapternumber> Using JSON in R with jsonlite package</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000093-jsonParsingPractice-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title"><yrchapternumber>21. </yrchapternumber> JSON Parsing Practice in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment-api-0000100-weatherDataApi-v002.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title"><yrchapternumber>22. </yrchapternumber> assignment - weather API</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Regular Expressions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0200200-a-introToRegularExpressions-v036.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title"><yrchapternumber>23. </yrchapternumber> regular expressions (regex)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./000260-PracticeWithRegulaExpressions-v003.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title"><yrchapternumber>24. </yrchapternumber> Practice with Regular Expressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0990100-cleaningData-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title"><yrchapternumber>25. </yrchapternumber> "Cleaning" data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Intro to dplyr</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0500100-a-tdyvrsDplyr-v005.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title"><yrchapternumber>26. </yrchapternumber> dplyr - getting and viewing the data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0500100-b-tdyvrsDplyr-v005.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title"><yrchapternumber>27. </yrchapternumber> dplyr verbs - select, filter, etc.</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true">
 <span class="menu-text">Relational databases and SQL</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0014-theBooksDatabase-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title"><yrchapternumber>28. </yrchapternumber> Get the data - "books database" and other tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0006-introToDatabases-v023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title"><yrchapternumber>29. </yrchapternumber>  "databases" and "database management systems"</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0500400-sqlSelectIntro-v003.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title"><yrchapternumber>30. </yrchapternumber> Intro to SQL Select ***(assumes some knowledge of dplyr)***</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0010-introToSql-v023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title"><yrchapternumber>31. </yrchapternumber> Intro to Relational Databases and SQL ***(no dplyr required)***</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0035-workingWithMultipleTables-v012.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title"><yrchapternumber>32. </yrchapternumber> Inner Joins.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0030-sqlFunctions_aggregateFunctions_groupBy_having-v019.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title"><yrchapternumber>33. </yrchapternumber> aggregate functions, group by, having</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0040-crossJoin-leftJoin-subquery-selfJoins-v023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title"><yrchapternumber>34. </yrchapternumber> more joins (cross/left/right/full), subqueries, set operations, case, self joins</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0050-commonTableExpressions-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title"><yrchapternumber>35. </yrchapternumber> Common Table Expressions (CTE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0200-otherSqlCommands-v002.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title"><yrchapternumber>36. </yrchapternumber> other commands: update/delete, create/drop/insert</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0900-sqlWindowFunctions-v002.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title"><yrchapternumber>37. </yrchapternumber> SQL "window" functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0915-workingWithSqliteDatabasesInR-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title"><yrchapternumber>38. </yrchapternumber> Working with SQLite databases in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0950-workingWithDatabasesInR-v010.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title"><yrchapternumber>39. </yrchapternumber> Working directly with databases in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql0935-dbNormalization-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title"><yrchapternumber>40. </yrchapternumber> Database Normalization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sql3000-sqlQuestions-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title"><yrchapternumber>41. </yrchapternumber> Database Questions (and Answers)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">Web Scraping</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./web-000205-introToXml-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title"><yrchapternumber>42. </yrchapternumber> Intro to XML</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./web-000220-parsingXmUsingR-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title"><yrchapternumber>43. </yrchapternumber> Parsing XML using R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./web-000300-internetArchitecture-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title"><yrchapternumber>44. </yrchapternumber> How a webpage gets to your browser</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./web-000325-introToHtmlAndCss-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title"><yrchapternumber>45. </yrchapternumber> Introduction to HTML and CSS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./web-000400-webscrapingContinued-015.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title"><yrchapternumber>46. </yrchapternumber> Web Scraping with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./web-000130-WebscrapingJavascriptSites-v004.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title"><yrchapternumber>47. </yrchapternumber> Scraping Dynamic (JavaScript) Websites</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./web-000420-practiceWithWebScraping-v001-ANSWERS-v002.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title"><yrchapternumber>48. </yrchapternumber> CSS Selector Questions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true">
 <span class="menu-text">Git and Github</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./github-000700-markdownGithubVsQuarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title"><yrchapternumber>49. </yrchapternumber> GitHub Markdown vs. Quarto (.qmd) Comparison</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true">
 <span class="menu-text">visualizations with ggplot2</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./050050-tdyvrsGgplot2-v0001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title"><yrchapternumber>50. </yrchapternumber> Intro to ggplot2</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000100-topics-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title"><yrchapternumber>51. </yrchapternumber> Topics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000200-bibliography-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title"><yrchapternumber>52. </yrchapternumber> Bibliography</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000300-whereToFindDatasets-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title"><yrchapternumber>53. </yrchapternumber> Where to find datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0000310-whereToFindApis-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title"><yrchapternumber>54. </yrchapternumber> Where to find APIs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0999000-toDo-v001.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title"><yrchapternumber>55. </yrchapternumber> Additional topics</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#note---this-page-is-for-ids2040---data-management-not-ids1020---intro-to-ids" id="toc-note---this-page-is-for-ids2040---data-management-not-ids1020---intro-to-ids" class="nav-link active" data-scroll-target="#note---this-page-is-for-ids2040---data-management-not-ids1020---intro-to-ids"><span class="header-section-number">30.1</span> NOTE - this page is for “IDS2040 - Data Management” (not “IDS1020 - Intro to IDS”)</a></li>
  <li><a href="#get-the-data" id="toc-get-the-data" class="nav-link" data-scroll-target="#get-the-data"><span class="header-section-number">30.2</span> Get the data</a>
  <ul class="collapse">
  <li><a href="#load-the-r-packages-well-neeed" id="toc-load-the-r-packages-well-neeed" class="nav-link" data-scroll-target="#load-the-r-packages-well-neeed"><span class="header-section-number">30.2.1</span> Load the R packages we’ll neeed</a></li>
  <li><a href="#download-the-file" id="toc-download-the-file" class="nav-link" data-scroll-target="#download-the-file"><span class="header-section-number">30.2.2</span> Download the file</a></li>
  <li><a href="#import-the-data-by-clicking-on-some-buttons" id="toc-import-the-data-by-clicking-on-some-buttons" class="nav-link" data-scroll-target="#import-the-data-by-clicking-on-some-buttons"><span class="header-section-number">30.2.3</span> Import the data by clicking on some buttons …</a></li>
  <li><a href="#import-the-data-by-typing-some-r-code" id="toc-import-the-data-by-typing-some-r-code" class="nav-link" data-scroll-target="#import-the-data-by-typing-some-r-code"><span class="header-section-number">30.2.4</span> Import the data by typing some R code …</a></li>
  </ul></li>
  <li><a href="#databases-and-sql" id="toc-databases-and-sql" class="nav-link" data-scroll-target="#databases-and-sql"><span class="header-section-number">30.3</span> Databases and SQL</a></li>
  <li><a href="#using-sql-in-r" id="toc-using-sql-in-r" class="nav-link" data-scroll-target="#using-sql-in-r"><span class="header-section-number">30.4</span> Using SQL in R</a></li>
  <li><a href="#dplyr-is-very-similar-to-the-sql-select-command" id="toc-dplyr-is-very-similar-to-the-sql-select-command" class="nav-link" data-scroll-target="#dplyr-is-very-similar-to-the-sql-select-command"><span class="header-section-number">30.5</span> dplyr is very similar to the SQL SELECT command</a></li>
  <li><a href="#sql-select-clauses-compared-with-dplyr-functions" id="toc-sql-select-clauses-compared-with-dplyr-functions" class="nav-link" data-scroll-target="#sql-select-clauses-compared-with-dplyr-functions"><span class="header-section-number">30.6</span> SQL SELECT “clauses” compared with dplyr “functions”</a></li>
  <li><a href="#order-of-the-clauses-is-important" id="toc-order-of-the-clauses-is-important" class="nav-link" data-scroll-target="#order-of-the-clauses-is-important"><span class="header-section-number">30.7</span> Order of the clauses is important</a></li>
  <li><a href="#is-sql-case-sensitive-yes-and-no" id="toc-is-sql-case-sensitive-yes-and-no" class="nav-link" data-scroll-target="#is-sql-case-sensitive-yes-and-no"><span class="header-section-number">30.8</span> Is SQL case sensitive? yes and no</a></li>
  <li><a href="#whitespace-in-sql-commands-is-ignored" id="toc-whitespace-in-sql-commands-is-ignored" class="nav-link" data-scroll-target="#whitespace-in-sql-commands-is-ignored"><span class="header-section-number">30.9</span> Whitespace in SQL commands is ignored</a></li>
  <li><a href="#intro-to-erds---i.e.-entity-relationship-diagrams" id="toc-intro-to-erds---i.e.-entity-relationship-diagrams" class="nav-link" data-scroll-target="#intro-to-erds---i.e.-entity-relationship-diagrams"><span class="header-section-number">30.10</span> Intro to ERDs - i.e.&nbsp;“Entity Relationship Diagrams”</a></li>
  <li><a href="#database-terminology---fields-entities-etc" id="toc-database-terminology---fields-entities-etc" class="nav-link" data-scroll-target="#database-terminology---fields-entities-etc"><span class="header-section-number">30.11</span> Database terminology - fields, entities, etc</a></li>
  <li><a href="#select-and-from-clauses" id="toc-select-and-from-clauses" class="nav-link" data-scroll-target="#select-and-from-clauses"><span class="header-section-number">30.12</span> SELECT and FROM clauses</a></li>
  <li><a href="#select-from" id="toc-select-from" class="nav-link" data-scroll-target="#select-from"><span class="header-section-number">30.13</span> SELECT * FROM …</a></li>
  <li><a href="#add-new-columns-in-select-clause" id="toc-add-new-columns-in-select-clause" class="nav-link" data-scroll-target="#add-new-columns-in-select-clause"><span class="header-section-number">30.14</span> add new columns in SELECT clause</a></li>
  <li><a href="#yrAggregateFunctions" id="toc-yrAggregateFunctions" class="nav-link" data-scroll-target="#yrAggregateFunctions"><span class="header-section-number">30.15</span> use aggregate functions in SELECT to create summary rows</a></li>
  <li><a href="#where-clause" id="toc-where-clause" class="nav-link" data-scroll-target="#where-clause"><span class="header-section-number">30.16</span> WHERE clause</a></li>
  <li><a href="#order-by-clause" id="toc-order-by-clause" class="nav-link" data-scroll-target="#order-by-clause"><span class="header-section-number">30.17</span> ORDER BY clause</a></li>
  <li><a href="#yrGroupBy" id="toc-yrGroupBy" class="nav-link" data-scroll-target="#yrGroupBy"><span class="header-section-number">30.18</span> GROUP BY clause</a></li>
  <li><a href="#limit-clause" id="toc-limit-clause" class="nav-link" data-scroll-target="#limit-clause"><span class="header-section-number">30.19</span> LIMIT clause</a>
  <ul class="collapse">
  <li><a href="#limit-vs-limit-offset" id="toc-limit-vs-limit-offset" class="nav-link" data-scroll-target="#limit-vs-limit-offset"><span class="header-section-number">30.19.1</span> LIMIT <m> &nbsp;&nbsp;&nbsp; vs &nbsp;&nbsp;&nbsp; LIMIT <m> OFFSET <n></n></m></m></a></li>
  </ul></li>
  <li><a href="#do-not-select-both-aggregate-and-non-aggregate-data" id="toc-do-not-select-both-aggregate-and-non-aggregate-data" class="nav-link" data-scroll-target="#do-not-select-both-aggregate-and-non-aggregate-data"><span class="header-section-number">30.20</span> DO NOT select both aggregate and non-aggregate data</a>
  <ul class="collapse">
  <li><a href="#example-of-incorrect-select-that-includes-both-aggregate-and-non-aggregated-columns" id="toc-example-of-incorrect-select-that-includes-both-aggregate-and-non-aggregated-columns" class="nav-link" data-scroll-target="#example-of-incorrect-select-that-includes-both-aggregate-and-non-aggregated-columns"><span class="header-section-number">30.20.1</span> Example of INCORRECT select that includes both aggregate and non-aggregated columns</a></li>
  <li><a href="#explanation" id="toc-explanation" class="nav-link" data-scroll-target="#explanation"><span class="header-section-number">30.20.2</span> Explanation</a></li>
  <li><a href="#ansi-sql-standard-vs-sqlite-vs-other-databases" id="toc-ansi-sql-standard-vs-sqlite-vs-other-databases" class="nav-link" data-scroll-target="#ansi-sql-standard-vs-sqlite-vs-other-databases"><span class="header-section-number">30.20.3</span> ANSI SQL standard vs SQLite vs other databases</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./sql0014-theBooksDatabase-v001.html">Relational databases and SQL</a></li><li class="breadcrumb-item"><a href="./0500400-sqlSelectIntro-v003.html"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title"><yrchapternumber>30. </yrchapternumber> Intro to SQL Select ***(assumes some knowledge of dplyr)***</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title"><yrchapternumber>30. </yrchapternumber> Intro to SQL Select <strong><em>(assumes some knowledge of dplyr)</em></strong></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="note---this-page-is-for-ids2040---data-management-not-ids1020---intro-to-ids" class="level2" data-number="30.1">
<h2 data-number="30.1" class="anchored" data-anchor-id="note---this-page-is-for-ids2040---data-management-not-ids1020---intro-to-ids"><span class="header-section-number">30.1</span> NOTE - this page is for “IDS2040 - Data Management” (not “IDS1020 - Intro to IDS”)</h2>
<p>NOTE - If you are in my “IDS1020 - Intro to IDS” class, this is NOT the page you should be reading. Rather, jump to the next section entitled “Relational Databases and SQL” and start from there.</p>
<p>This page is intended for my “IDS460 - Data Management” class. The info below assumes that you have some knowledge of the dplyr package in R (which was covered in the previous section). After you get a basic idea of what the SQL SELECT statement does and how it is very similar to the dplyr functions, you can move onto the next section entitled “Relational Databases and SQL” and continue with that information.</p>
</section>
<section id="get-the-data" class="level2" data-number="30.2">
<h2 data-number="30.2" class="anchored" data-anchor-id="get-the-data"><span class="header-section-number">30.2</span> Get the data</h2>
<p>The data we are using in this section contains information about salespeople who are employees of a company. Each row of the data contains info about one salesperson. The salespeople get paid some “base pay” as well as a commission that is a percent of the total dollar amount of sales they make.</p>
<p>Follow the instructions below to get the data and start using it in R.</p>
<section id="load-the-r-packages-well-neeed" class="level3" data-number="30.2.1">
<h3 data-number="30.2.1" class="anchored" data-anchor-id="load-the-r-packages-well-neeed"><span class="header-section-number">30.2.1</span> Load the R packages we’ll neeed</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(tibble)){<span class="fu">install.packages</span>(<span class="st">"tibble"</span>);<span class="fu">require</span>(tibble);}</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(dplyr)){<span class="fu">install.packages</span>(<span class="st">"dplyr"</span>);<span class="fu">require</span>(dplyr);}</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(readr)){<span class="fu">install.packages</span>(<span class="st">"readr"</span>);<span class="fu">require</span>(readr);}</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(sqldf)){<span class="fu">install.packages</span>(<span class="st">"sqldf"</span>);<span class="fu">require</span>(sqldf);}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="download-the-file" class="level3" data-number="30.2.2">
<h3 data-number="30.2.2" class="anchored" data-anchor-id="download-the-file"><span class="header-section-number">30.2.2</span> Download the file</h3>
<p>The data is contained in a csv file. If you’d like to follow along with this tutorial on your own computer you can download the .csv file we are using by clicking <a href="data/salespeople-v002.csv">here</a>.</p>
</section>
<section id="import-the-data-by-clicking-on-some-buttons" class="level3" data-number="30.2.3">
<h3 data-number="30.2.3" class="anchored" data-anchor-id="import-the-data-by-clicking-on-some-buttons"><span class="header-section-number">30.2.3</span> Import the data by clicking on some buttons …</h3>
<ul>
<li><p>The code in the next section below uses read_csv function to read the data into R. If you are not comfortable with R, I recommend that you instead, follow the instructions starting in the next bullet to import the data into R.</p></li>
<li><p>If you are not familiar with R, you may have some trouble running the read_csv() code shown below. Instead, I recommend that you follow the following instructions to import the file into R.</p>
<p>To do so, click on “Import Dataset” button on the “Environment” tab (usually found in the upper-right-hand window pane in RStudio).</p>
<p>Choose “From Text (base)” and locate your file. You should see something like this:</p>
<p><img src="images/importDatasetFromCsvBase.png" class="img-fluid" style="width:75.0%"></p>
<p>Make sure to change the “Name” portion (see circled section in picture) to read “sales”, then press the “import” button. This will open up a new tab in RStudio that shows the contents of the file. You can safely navigate away from this tab or close the tab and the data will remain imported and can be seen by typing “sales” (without the “quotes”).</p></li>
</ul>
</section>
<section id="import-the-data-by-typing-some-r-code" class="level3" data-number="30.2.4">
<h3 data-number="30.2.4" class="anchored" data-anchor-id="import-the-data-by-typing-some-r-code"><span class="header-section-number">30.2.4</span> Import the data by typing some R code …</h3>
<p>The following code reads the data into R. Alternatively, you can follow the instructions above to click on some buttons to import the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the data into a tibble</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that the following code uses the readr::read_csv function from the readr</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># package which is part of the tidyverse collection of packages. </span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># This function is similar to the base-R read.csv function.</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># read_csv returns a tibble, which is the data structure that the </span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># tidyverse packages use in lieu of dataframes. A tibble is basically</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># a dataframe with extra features.</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># By contrast, the base-r read.csv function returns a dataframe.</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>sales <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">"salespeople-v002.csv"</span>, <span class="at">na=</span><span class="fu">c</span>(<span class="st">""</span>,<span class="st">"NULL"</span>), <span class="at">show_col_types=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="databases-and-sql" class="level2" data-number="30.3">
<h2 data-number="30.3" class="anchored" data-anchor-id="databases-and-sql"><span class="header-section-number">30.3</span> Databases and SQL</h2>
<p>A database is an organized collection of data that is designed to be accessed and manipulated by computer programs. We’ll cover a little more about exactly what a database is and how it differs from Excel, R and other programs in the next section of this book. Below is just a brief explanation to give you some background before we start getting into the details of the SQL language that is used to communicate with databases.</p>
<p>A “relational database” is a type of database in which data is arranged in “tables” that are organized into “rows” and “columns”. A “relational database table” is very similar to an R dataframe or tibble. Relational databases are controlled and managed with software known as “Relational DataBase Management System” (RDBMS) software. Relational database technology dates back to the 1970s and has been around long before R has been around. Relational databases are used by just about every major company all around the world.</p>
<p>“Structured Query Language” (or SQL for short - pronounced “sequel”) is the standard language that is used to communicate with a DBMS to manage and manipulate the data in a Relational Database. SQL has many different commands. One of the most important SQL commands for data analysts to know is the SQL “SELECT” command. It is this command that is used to extract data from a database and organize the data into a desired form. We will focus in this section on an intro to the SQL SELECT statement.</p>
</section>
<section id="using-sql-in-r" class="level2" data-number="30.4">
<h2 data-number="30.4" class="anchored" data-anchor-id="using-sql-in-r"><span class="header-section-number">30.4</span> Using SQL in R</h2>
<p>As we said above, R is NOT a Database Management System. However SQL is a very popular language. Many technologists come to R, already having a deep knowledge of the SQL language. Therefore it is nice to know that the SQL language can also be used to manipulate R dataframes. This is possible because R dataframes are very, very similar in structure to Relational Database “tables” (i.e.&nbsp;they have rows, columns, column names and specific datatypes for each column).</p>
<p>The R “sqldf” package includes a function named “sqldf” which takes a SQL command as its argument. Wherever the SQL command refers to the name of a relational database “table”, sqldf runs the SQL command using the R dataframe with that name.</p>
<p>There are other more advanced ways for R to connect to SQL databases (DB) and database management systems (DBMS). We will cover the more advanced ways later. For now, sqldf will suit our purposes for this intro.</p>
</section>
<section id="dplyr-is-very-similar-to-the-sql-select-command" class="level2" data-number="30.5">
<h2 data-number="30.5" class="anchored" data-anchor-id="dplyr-is-very-similar-to-the-sql-select-command"><span class="header-section-number">30.5</span> dplyr is very similar to the SQL SELECT command</h2>
<p>The designers of dplyr got inspiration for many of their ideas from SQL. Therefore once you know the basics of dplyr it should be very easy to transfer that knowledge to learning the SQL SELECT statement.</p>
<p>The following examples show how the concepts you learned in the previous section about dplyr carry over to the SQL SELECT statement.</p>
<p>The English word “query” means a question. <strong>A SQL SELECT statement is often referred to as a database “query”</strong>. In essence a SQL SELECT statement in essence asks the database a question and gets back an answer.</p>
</section>
<section id="sql-select-clauses-compared-with-dplyr-functions" class="level2" data-number="30.6">
<h2 data-number="30.6" class="anchored" data-anchor-id="sql-select-clauses-compared-with-dplyr-functions"><span class="header-section-number">30.6</span> SQL SELECT “clauses” compared with dplyr “functions”</h2>
<p>While dplyr uses different “functions”, the SQL SELECT statement is comprised of different “clauses”. The clauses in the SQL SELECT statement are listed below. We will elaborate on the details of these clauses in the sections below.</p>
<ul>
<li><p>SELECT</p>
<p>This is used to “select” the columns you want - similar to dplyr select function.</p></li>
<li><p>FROM</p>
<p>Used to specify which “tables” contain the information you will be working with. In dplyr this is accomplished via the first argument, .data, of each of the dplyr “verb” functions that we learned about in the previous section.</p></li>
<li><p>WHERE</p>
<p>Choose the rows you want. Directly analogous to the dplyr “filter” function.</p></li>
<li><p>GROUP BY</p>
<p>Directly analogous to the dplyr “group_by” function.</p></li>
<li><p>HAVING</p>
<p>This is also similar to the dplyr “filter” function. We will learn later how this differs from the SQL SELECT WHERE clause.</p></li>
<li><p>ORDER BY</p>
<p>Directly analogous to the dplyr “arrange” function</p></li>
<li><p>LIMIT</p>
<p>Directly analogous to the dplyr print(n=…) function or the dplyr slice_head(n=…) function.</p></li>
</ul>
</section>
<section id="order-of-the-clauses-is-important" class="level2" data-number="30.7">
<h2 data-number="30.7" class="anchored" data-anchor-id="order-of-the-clauses-is-important"><span class="header-section-number">30.7</span> Order of the clauses is important</h2>
<p>A SQL SELECT statement may contain some or all of the above clauses. Only the SELECT clause is absolutely required. If the SQL SELECT statement contains more than one clause then whichever clauses do appear must appear in the order listed above.</p>
</section>
<section id="is-sql-case-sensitive-yes-and-no" class="level2" data-number="30.8">
<h2 data-number="30.8" class="anchored" data-anchor-id="is-sql-case-sensitive-yes-and-no"><span class="header-section-number">30.8</span> Is SQL case sensitive? yes and no</h2>
<p>Different SQL products treat case sensitivity differently. In general the names of tables and columns ARE case sensitive. The “keywords” of the language are generally NOT case sensitive. However, it is often the convention of many SQL books and references to show SQL keywords in UPPER CASE. We have done that below but it is not strictly necessary.</p>
</section>
<section id="whitespace-in-sql-commands-is-ignored" class="level2" data-number="30.9">
<h2 data-number="30.9" class="anchored" data-anchor-id="whitespace-in-sql-commands-is-ignored"><span class="header-section-number">30.9</span> Whitespace in SQL commands is ignored</h2>
<p>A SQL command may be written entirely on one line. However, extra whitespace (i.e.&nbsp;spaces, tabs, newlines) may be added to make the code more readable. It is common to start each SQL SELECT statement clause on a new line and to add extra whitespace to make the code more readable. In general we tried to follow that practice in the code.</p>
</section>
<section id="intro-to-erds---i.e.-entity-relationship-diagrams" class="level2" data-number="30.10">
<h2 data-number="30.10" class="anchored" data-anchor-id="intro-to-erds---i.e.-entity-relationship-diagrams"><span class="header-section-number">30.10</span> Intro to ERDs - i.e.&nbsp;“Entity Relationship Diagrams”</h2>
<p>An “Entity Relationship Diagram” (ERD) is a diagram that highlights the structure of the tables in a database (in database terminology tables are also known as “entity sets” or “entity types” - see below). The ERD does NOT show the data in the tables, just the structure of the tables. The following is an ERD for the sales data we have been using.</p>
<p><em>Note that so far we’ve only been using one table. An ERD gets more complicated when</em> <em>a database contains several tables. We will revisit ERDs again later.</em></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">erDiagram
    SALES {
        first character "employee first name"
        last character "employee last name"
        title character "employee title"
        region character "region that employee sells to"
        baseInThousands numeric "employee's base pay (in thousands)"
        salesInThousands numeric "total sales dollars (in thousands)"
        yearsWithCompany numeric "number years employee with company"
    }
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>The table name is shown at the top</li>
<li>Under the table name
<ul>
<li>The 1st column contains the names of the table’s fields (i.e.&nbsp;columns)</li>
<li>The 2nd column contains the datatype of the fields</li>
<li>The 3rd column contains a description of the field</li>
</ul></li>
</ul>
<p>Some Entity Relationship Diagrams don’t contain as much information. Often an ERD will NOT contain a description of the fields. This is still a “valid” ERD, just not as descriptive.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">erDiagram
    SALES {
        first character
        last character
        title character
        region character
        baseInThousands numeric
        salesInThousands numeric
        yearsWithCompany numeric
    }
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>In the extreme case, an ERD may only contain the names of the tables. This type of ERD is only really useful when the database contains multiple tables.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">erDiagram
    SALES
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="database-terminology---fields-entities-etc" class="level2" data-number="30.11">
<h2 data-number="30.11" class="anchored" data-anchor-id="database-terminology---fields-entities-etc"><span class="header-section-number">30.11</span> Database terminology - fields, entities, etc</h2>
<p>There are different terms used to refer to the rows and columns of a table, dataframe or tibble. Statisticians often refer to each row of a table as an observation and each column of a table as a variable.</p>
<p>In the world of databases, a column can be referred to as a “column” or a “field”. Rows are referred to as just “rows” but sometimes are referred to as “records” or “entities”. Often an entire table is referred to as an “entity” (technically a table, which is a collection of rows, is an “entity set” or an “entity type”).</p>
<p>The truth is that not many people use the word “entity” or “entity set”. However, an “Entity Relationship Diagram” is used to show the tables in a database and how the tables are “related” to each other.</p>
<p>In this section we are just focusing on a single table. In a later sections, we’ll learn more about “relationships” between multiple tables and how the relationships are displayed on an Entity Relationship Diagram.</p>
</section>
<section id="select-and-from-clauses" class="level2" data-number="30.12">
<h2 data-number="30.12" class="anchored" data-anchor-id="select-and-from-clauses"><span class="header-section-number">30.12</span> SELECT and FROM clauses</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The SELECT clause specifies which columns you want.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The FROM clause specifies the table (or tables) that contain the data.</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT title, first, last</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             title  first       last
1          Manager    Joe      Smith
2      Salesperson    Sam        Lee
3      Salesperson    Sue  Sallinger
4  Sr. Salesperson   Barb      Brown
5          Manager   Jack     Martin
6  Sr. Salesperson   Kate      Carey
7      Salesperson    Emy    Parsons
8      Salesperson Monica        Oja
9  Sr. Salesperson    Jim Kuruzovich
10         Manager   Zeke      Cohen
11     Salesperson   Zeke      Smith
12     Salesperson    Amy   Markovic
13 Sr. Salesperson    Joe Washington
14         Manager    Sam    Lincoln
15 Sr. Salesperson    Sue      Aames
16     Salesperson   Barb      Aames
17     Salesperson   Jack      Aames
18 Sr. Salesperson   Kate   Zeitchik
19         Manager    Emy   Zeitchik
20     Salesperson Monica   Zeitchik
21     Salesperson    Jim      Brown
22 Sr. Salesperson  Larry      Green
23         Manager  Laura      White
24 Sr. Salesperson   Hugh      Black</code></pre>
</div>
</div>
</section>
<section id="select-from" class="level2" data-number="30.13">
<h2 data-number="30.13" class="anchored" data-anchor-id="select-from"><span class="header-section-number">30.13</span> SELECT * FROM …</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SELECT * in SQL is similar to select(everything()) in dplyr.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># * is an abbreviation for all of the column names.</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT *</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    first       last           title region baseInThousands salesInThousands yearsWithCompany
1     Joe      Smith         Manager    usa              40              100               10
2     Sam        Lee     Salesperson    usa              40              200                6
3     Sue  Sallinger     Salesperson   asia              30              150               10
4    Barb      Brown Sr. Salesperson   asia              35               79                4
5    Jack     Martin         Manager europe              20               40                3
6    Kate      Carey Sr. Salesperson europe              20               69                2
7     Emy    Parsons     Salesperson africa              25               87                3
8  Monica        Oja     Salesperson africa              35               98               10
9     Jim Kuruzovich Sr. Salesperson    usa              35              140                3
10   Zeke      Cohen         Manager    usa              30              250               10
11   Zeke      Smith     Salesperson   asia              20              120                3
12    Amy   Markovic     Salesperson   asia              46              340                3
13    Joe Washington Sr. Salesperson europe              33              370                2
14    Sam    Lincoln         Manager europe              30              500                2
15    Sue      Aames Sr. Salesperson africa              35              600               10
16   Barb      Aames     Salesperson    usa              21              255                7
17   Jack      Aames     Salesperson    usa              43              105                4
18   Kate   Zeitchik Sr. Salesperson    usa              50              187                4
19    Emy   Zeitchik         Manager   asia              34              166                4
20 Monica   Zeitchik     Salesperson   asia              23              184                1
21    Jim      Brown     Salesperson europe              50              167                2
22  Larry      Green Sr. Salesperson europe              20              113                4
23  Laura      White         Manager africa              20              281                8
24   Hugh      Black Sr. Salesperson africa              40              261                9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Unfortunately, the SQL SELECT * is not as smart as the everything() function in dplyr.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># In dplyr, everything() does not include columns that you already typed.</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># In SQL, the * always includes ALL columns. Therefore the following</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># query displays the title and region columns a 2nd time due to the *</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT title, region, *</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             title region  first       last           title region baseInThousands salesInThousands yearsWithCompany
1          Manager    usa    Joe      Smith         Manager    usa              40              100               10
2      Salesperson    usa    Sam        Lee     Salesperson    usa              40              200                6
3      Salesperson   asia    Sue  Sallinger     Salesperson   asia              30              150               10
4  Sr. Salesperson   asia   Barb      Brown Sr. Salesperson   asia              35               79                4
5          Manager europe   Jack     Martin         Manager europe              20               40                3
6  Sr. Salesperson europe   Kate      Carey Sr. Salesperson europe              20               69                2
7      Salesperson africa    Emy    Parsons     Salesperson africa              25               87                3
8      Salesperson africa Monica        Oja     Salesperson africa              35               98               10
9  Sr. Salesperson    usa    Jim Kuruzovich Sr. Salesperson    usa              35              140                3
10         Manager    usa   Zeke      Cohen         Manager    usa              30              250               10
11     Salesperson   asia   Zeke      Smith     Salesperson   asia              20              120                3
12     Salesperson   asia    Amy   Markovic     Salesperson   asia              46              340                3
13 Sr. Salesperson europe    Joe Washington Sr. Salesperson europe              33              370                2
14         Manager europe    Sam    Lincoln         Manager europe              30              500                2
15 Sr. Salesperson africa    Sue      Aames Sr. Salesperson africa              35              600               10
16     Salesperson    usa   Barb      Aames     Salesperson    usa              21              255                7
17     Salesperson    usa   Jack      Aames     Salesperson    usa              43              105                4
18 Sr. Salesperson    usa   Kate   Zeitchik Sr. Salesperson    usa              50              187                4
19         Manager   asia    Emy   Zeitchik         Manager   asia              34              166                4
20     Salesperson   asia Monica   Zeitchik     Salesperson   asia              23              184                1
21     Salesperson europe    Jim      Brown     Salesperson europe              50              167                2
22 Sr. Salesperson europe  Larry      Green Sr. Salesperson europe              20              113                4
23         Manager africa  Laura      White         Manager africa              20              281                8
24 Sr. Salesperson africa   Hugh      Black Sr. Salesperson africa              40              261                9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The only thing you can do in a select statement without a FROM clause</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># is to perform calculations without data from a table.</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT 3+2, 100*5"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  3+2 100*5
1   5   500</code></pre>
</div>
</div>
</section>
<section id="add-new-columns-in-select-clause" class="level2" data-number="30.14">
<h2 data-number="30.14" class="anchored" data-anchor-id="add-new-columns-in-select-clause"><span class="header-section-number">30.14</span> add new columns in SELECT clause</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># In dplyr, to add new columns you use the mutate function.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># In the SQL SELECT command this is accomplished as part of the SELECT clause.</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># To add new columns that are calculated from other columns</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># simply add the calculations to the select clause.</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT first, last, salesInThousands, 0.1 * salesInThousands</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="st">       "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    first       last salesInThousands 0.1 * salesInThousands
1     Joe      Smith              100                   10.0
2     Sam        Lee              200                   20.0
3     Sue  Sallinger              150                   15.0
4    Barb      Brown               79                    7.9
5    Jack     Martin               40                    4.0
6    Kate      Carey               69                    6.9
7     Emy    Parsons               87                    8.7
8  Monica        Oja               98                    9.8
9     Jim Kuruzovich              140                   14.0
10   Zeke      Cohen              250                   25.0
11   Zeke      Smith              120                   12.0
12    Amy   Markovic              340                   34.0
13    Joe Washington              370                   37.0
14    Sam    Lincoln              500                   50.0
15    Sue      Aames              600                   60.0
16   Barb      Aames              255                   25.5
17   Jack      Aames              105                   10.5
18   Kate   Zeitchik              187                   18.7
19    Emy   Zeitchik              166                   16.6
20 Monica   Zeitchik              184                   18.4
21    Jim      Brown              167                   16.7
22  Larry      Green              113                   11.3
23  Laura      White              281                   28.1
24   Hugh      Black              261                   26.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can give the new column a unique name by following the definition</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># of the column with "AS columnName".</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT first, last, salesInThousands, 0.1 * salesInThousands as commission</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="st">       "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    first       last salesInThousands commission
1     Joe      Smith              100       10.0
2     Sam        Lee              200       20.0
3     Sue  Sallinger              150       15.0
4    Barb      Brown               79        7.9
5    Jack     Martin               40        4.0
6    Kate      Carey               69        6.9
7     Emy    Parsons               87        8.7
8  Monica        Oja               98        9.8
9     Jim Kuruzovich              140       14.0
10   Zeke      Cohen              250       25.0
11   Zeke      Smith              120       12.0
12    Amy   Markovic              340       34.0
13    Joe Washington              370       37.0
14    Sam    Lincoln              500       50.0
15    Sue      Aames              600       60.0
16   Barb      Aames              255       25.5
17   Jack      Aames              105       10.5
18   Kate   Zeitchik              187       18.7
19    Emy   Zeitchik              166       16.6
20 Monica   Zeitchik              184       18.4
21    Jim      Brown              167       16.7
22  Larry      Green              113       11.3
23  Laura      White              281       28.1
24   Hugh      Black              261       26.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The word "AS" is actually optional. The following adds two new columns</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># but does not use the word AS. All you need is the definition of the column</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># followed by a space followed by the name of the new column.</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT first, last, baseInThousands,  </span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="st">              salesInThousands, 0.1 * salesInThousands commission, </span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="st">              salesInThousands * 0.1 + baseInThousands takeHome</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="st">       WHERE region='africa'</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="st">       "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   first    last baseInThousands salesInThousands commission takeHome
1    Emy Parsons              25               87        8.7     33.7
2 Monica     Oja              35               98        9.8     44.8
3    Sue   Aames              35              600       60.0     95.0
4  Laura   White              20              281       28.1     48.1
5   Hugh   Black              40              261       26.1     66.1</code></pre>
</div>
</div>
</section>
<section id="yrAggregateFunctions" class="level2" data-number="30.15">
<h2 data-number="30.15" class="anchored" data-anchor-id="yrAggregateFunctions"><span class="header-section-number">30.15</span> use aggregate functions in SELECT to create summary rows</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The dplyr summarize function is used to summarize (or aggregate) info from</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># several rows into a single row. </span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># In the SQL SELECT statement, this is accomplished by simply using</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># aggregate functions in the select clause.</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># SQL has several built in standard aggregate functions</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co">#   count(*) - similar to n() in dplyr - we'll discuss why the * is there later</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co">#   avg(SOME_COLUMN)</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co">#   max(SOME_COLUMN)</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co">#   min(SOME_COLUMN)</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"select count(*), avg(baseInThousands), max(baseInThousands)</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY region ASC, salesInThousands DESC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  count(*) avg(baseInThousands) max(baseInThousands)
1       24             32.29167                   50</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># As shown above we can assign names to the new columns.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Again, as we said above, the word "AS" is optional. The following statement</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># would work exactly the same way if we did not have the word "AS"</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT count(*) as numberOfEmployees, </span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="st">              avg(baseInThousands) AS averagebaseInThousands, </span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="st">              max(baseInThousands) AS maxbaseInThousands</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY region ASC, salesInThousands DESC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  numberOfEmployees averagebaseInThousands maxbaseInThousands
1                24               32.29167                 50</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This is the same query as above.</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This version does not have the word "AS".</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The results are exactly the same.</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT count(*) numberOfEmployees, </span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="st">              avg(baseInThousands) averagebaseInThousands, </span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="st">              max(baseInThousands) maxbaseInThousands</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY region ASC, salesInThousands DESC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  numberOfEmployees averagebaseInThousands maxbaseInThousands
1                24               32.29167                 50</code></pre>
</div>
</div>
</section>
<section id="where-clause" class="level2" data-number="30.16">
<h2 data-number="30.16" class="anchored" data-anchor-id="where-clause"><span class="header-section-number">30.16</span> WHERE clause</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># WHERE is directly analogous to the dplyr filter function.</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The WHERE clause identifies the rows that will be returned.</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># It takes a logical expression that uses the names of the columns.</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># For every row the SELECT statement analyzes the row and calculates the</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># result of the logical expression for that row. If the logical expression</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># for a row is TRUE you get the row back. If not you do not get the row.</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT *</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="st">       WHERE salesInThousands &lt; 100"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   first    last           title region baseInThousands salesInThousands yearsWithCompany
1   Barb   Brown Sr. Salesperson   asia              35               79                4
2   Jack  Martin         Manager europe              20               40                3
3   Kate   Carey Sr. Salesperson europe              20               69                2
4    Emy Parsons     Salesperson africa              25               87                3
5 Monica     Oja     Salesperson africa              35               98               10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This query uses aggregate functions in the SELECT but does NOT have a WHERE.</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Therefore the result is a summary of ALL rows in the table.</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT count(*), min(baseInThousands), max(baseInThousands), avg(baseInThousands)</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  count(*) min(baseInThousands) max(baseInThousands) avg(baseInThousands)
1       24                   20                   50             32.29167</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This is the same query but adds WHERE region='asia'.</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># As a result the summary row only reflects info about the rows for 'asia'.</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Notice the there are fewer rows in the count(*) column and some of the</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># other summary statistics are also different.</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT count(*), min(baseInThousands), max(baseInThousands), avg(baseInThousands)</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="st">       WHERE region='asia'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  count(*) min(baseInThousands) max(baseInThousands) avg(baseInThousands)
1        6                   20                   46             31.33333</code></pre>
</div>
</div>
</section>
<section id="order-by-clause" class="level2" data-number="30.17">
<h2 data-number="30.17" class="anchored" data-anchor-id="order-by-clause"><span class="header-section-number">30.17</span> ORDER BY clause</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The ORDER BY clause is directly anaogous to dplyr's arrange function</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT *</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="st">       WHERE salesInThousands &lt; 100</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER By salesInThousands"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   first    last           title region baseInThousands salesInThousands yearsWithCompany
1   Jack  Martin         Manager europe              20               40                3
2   Kate   Carey Sr. Salesperson europe              20               69                2
3   Barb   Brown Sr. Salesperson   asia              35               79                4
4    Emy Parsons     Salesperson africa              25               87                3
5 Monica     Oja     Salesperson africa              35               98               10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just as with dplyr's arrange function the rows can be ordered</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># from largest to smallest by specifying desc, i.e. a descending order</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># for the values of a column.</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT *</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="st">       WHERE salesInThousands &lt; 100</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY salesInThousands DESC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   first    last           title region baseInThousands salesInThousands yearsWithCompany
1 Monica     Oja     Salesperson africa              35               98               10
2    Emy Parsons     Salesperson africa              25               87                3
3   Barb   Brown Sr. Salesperson   asia              35               79                4
4   Kate   Carey Sr. Salesperson europe              20               69                2
5   Jack  Martin         Manager europe              20               40                3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just as with dplyr's arrange function you can specify that the order</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># of the rows should depend on multiple columns. </span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The first column specified is used to order all of the rows.</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Subsequent columns mentioned in ORDER By are used only for rows</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="co"># in which the values for the earlier columns are the same.</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Each column could have an ascending (asc) or descending (desc) order.</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="co"># If neither asc nor desc is specified, then the default is an ascending order.</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT *</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY region ASC, salesInThousands DESC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    first       last           title region baseInThousands salesInThousands yearsWithCompany
1     Sue      Aames Sr. Salesperson africa              35              600               10
2   Laura      White         Manager africa              20              281                8
3    Hugh      Black Sr. Salesperson africa              40              261                9
4  Monica        Oja     Salesperson africa              35               98               10
5     Emy    Parsons     Salesperson africa              25               87                3
6     Amy   Markovic     Salesperson   asia              46              340                3
7  Monica   Zeitchik     Salesperson   asia              23              184                1
8     Emy   Zeitchik         Manager   asia              34              166                4
9     Sue  Sallinger     Salesperson   asia              30              150               10
10   Zeke      Smith     Salesperson   asia              20              120                3
11   Barb      Brown Sr. Salesperson   asia              35               79                4
12    Sam    Lincoln         Manager europe              30              500                2
13    Joe Washington Sr. Salesperson europe              33              370                2
14    Jim      Brown     Salesperson europe              50              167                2
15  Larry      Green Sr. Salesperson europe              20              113                4
16   Kate      Carey Sr. Salesperson europe              20               69                2
17   Jack     Martin         Manager europe              20               40                3
18   Barb      Aames     Salesperson    usa              21              255                7
19   Zeke      Cohen         Manager    usa              30              250               10
20    Sam        Lee     Salesperson    usa              40              200                6
21   Kate   Zeitchik Sr. Salesperson    usa              50              187                4
22    Jim Kuruzovich Sr. Salesperson    usa              35              140                3
23   Jack      Aames     Salesperson    usa              43              105                4
24    Joe      Smith         Manager    usa              40              100               10</code></pre>
</div>
</div>
</section>
<section id="yrGroupBy" class="level2" data-number="30.18">
<h2 data-number="30.18" class="anchored" data-anchor-id="yrGroupBy"><span class="header-section-number">30.18</span> GROUP BY clause</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The GROUP BY clause in SQL is directly analogous to the group_by function in dplyr.</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># All of the rows that have the same value for the specified GROUP BY columns</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># are aggregated (i.e. summarized) in a single line of output.</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># GROUP BY should only be used if the SELECT clause includes aggregate functions. </span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT title, count(*), avg(baseInThousands) avgBase, max(baseInThousands) maxBase</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="st">       GROUP BY title</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY title"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            title count(*) avgBase maxBase
1         Manager        6    29.0      40
2     Salesperson       10    33.3      50
3 Sr. Salesperson        8    33.5      50</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grouping by a different column - region</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT region, count(*), avg(baseInThousands) avgBase, max(baseInThousands) maxBase</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="st">       GROUP BY region</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY region"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  region count(*)  avgBase maxBase
1 africa        5 31.00000      40
2   asia        6 31.33333      46
3 europe        6 28.83333      50
4    usa        7 37.00000      50</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just as with dplyr, the groups can be defined by more than one column.</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The following query treats all of the rows that match in both the</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># region and title columns as a single group.</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co"># For example, all of the original rows from the sales table</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co"># that have a title of "Salesperson" and a region of "asia" </span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="co"># are considered to be part of the same group and are summarized </span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co"># in a single row of the output.</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT title, region, count(*), avg(baseInThousands) avgBase, max(baseInThousands) maxBase</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="st">       GROUP BY title, region</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY title, region"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             title region count(*)  avgBase maxBase
1          Manager africa        1 20.00000      20
2          Manager   asia        1 34.00000      34
3          Manager europe        2 25.00000      30
4          Manager    usa        2 35.00000      40
5      Salesperson africa        2 30.00000      35
6      Salesperson   asia        4 29.75000      46
7      Salesperson europe        1 50.00000      50
8      Salesperson    usa        3 34.66667      43
9  Sr. Salesperson africa        2 37.50000      40
10 Sr. Salesperson   asia        1 35.00000      35
11 Sr. Salesperson europe        3 24.33333      33
12 Sr. Salesperson    usa        2 42.50000      50</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A similar query without a GROUP BY returns just a single row that</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># summarizes the data from all rows of the table.</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT count(*), avg(baseInThousands) avgBase, max(baseInThousands) maxBase</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  count(*)  avgBase maxBase
1       24 32.29167      50</code></pre>
</div>
</div>
</section>
<section id="limit-clause" class="level2" data-number="30.19">
<h2 data-number="30.19" class="anchored" data-anchor-id="limit-clause"><span class="header-section-number">30.19</span> LIMIT clause</h2>
<p>The LIMIT clause is similar to print(n=…) and slice_head(n=…) with dplyr. It limits the number of rows returned to the first few that would have been returned had the query not included the LIMIT clause.</p>
<p>LIMIT is often used in combination with the ORDER BY clause.</p>
<p>LIMIT must come at the very end of the SQL statement.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT *</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY salesInThousands desc</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="st">       LIMIT 10"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   first       last           title region baseInThousands salesInThousands yearsWithCompany
1    Sue      Aames Sr. Salesperson africa              35              600               10
2    Sam    Lincoln         Manager europe              30              500                2
3    Joe Washington Sr. Salesperson europe              33              370                2
4    Amy   Markovic     Salesperson   asia              46              340                3
5  Laura      White         Manager africa              20              281                8
6   Hugh      Black Sr. Salesperson africa              40              261                9
7   Barb      Aames     Salesperson    usa              21              255                7
8   Zeke      Cohen         Manager    usa              30              250               10
9    Sam        Lee     Salesperson    usa              40              200                6
10  Kate   Zeitchik Sr. Salesperson    usa              50              187                4</code></pre>
</div>
</div>
<section id="limit-vs-limit-offset" class="level3" data-number="30.19.1">
<h3 data-number="30.19.1" class="anchored" data-anchor-id="limit-vs-limit-offset"><span class="header-section-number">30.19.1</span> LIMIT <m> &nbsp;&nbsp;&nbsp; vs &nbsp;&nbsp;&nbsp; LIMIT <m> OFFSET <n></n></m></m></h3>
<p>In general the limit clause has two different forms:</p>
<pre><code>      &lt;SOME SELECT STATEMENT&gt;
      limit M</code></pre>
<p>(where M is an integer) results in only the first M rows of data from what would normally have been displayed had the LIMIT clause not been specified.</p>
<pre><code>      &lt;SOME SELECT STATEMENT&gt;
      limit M offset N</code></pre>
<p>(where both M and N are integers)<br>
starts the output from the N+1’th row of what would normally have been displayed without the limit clause and then displays the next M rows of data.</p>
<p>For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first 3 people</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT *</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY last, first</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="st">       LIMIT 3"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  first  last           title region baseInThousands salesInThousands yearsWithCompany
1  Barb Aames     Salesperson    usa              21              255                7
2  Jack Aames     Salesperson    usa              43              105                4
3   Sue Aames Sr. Salesperson africa              35              600               10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the next 3 people</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT *</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY last, first</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="st">       LIMIT 3 OFFSET 3"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  first  last           title region baseInThousands salesInThousands yearsWithCompany
1  Hugh Black Sr. Salesperson africa              40              261                9
2  Barb Brown Sr. Salesperson   asia              35               79                4
3   Jim Brown     Salesperson europe              50              167                2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the next 3 people</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"SELECT *</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="st">       FROM sales</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="st">       ORDER BY last, first</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="st">       LIMIT 3 OFFSET 6"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  first  last           title region baseInThousands salesInThousands yearsWithCompany
1  Kate Carey Sr. Salesperson europe              20               69                2
2  Zeke Cohen         Manager    usa              30              250               10
3 Larry Green Sr. Salesperson europe              20              113                4</code></pre>
</div>
</div>
<p>Note that the LIMIT clause is not standard SQL - some SQL flavors do not contain a LIMIT clause. However, the LIMIT clause or something similar is part of most SQL flavors.</p>
</section>
</section>
<section id="do-not-select-both-aggregate-and-non-aggregate-data" class="level2" data-number="30.20">
<h2 data-number="30.20" class="anchored" data-anchor-id="do-not-select-both-aggregate-and-non-aggregate-data"><span class="header-section-number">30.20</span> DO NOT select both aggregate and non-aggregate data</h2>
<p><strong>SUMMARY OF THIS SECTION:</strong> <strong>If a SELECT clause includes aggregate functions then the SELECT clause should NOT</strong> <strong>include non-aggregated columns, unless those columns are part of the</strong> <strong>GROUP BY clause.</strong> <em>(The rest of this section explains this rule.)</em> <strong>IMPORTANT</strong> - if you don’t follow this rule, then you will NOT get an error but your output will be misleading.</p>
<p><em>Before reading the rest of this section I highly recommend that you review</em> <em>the sections above on</em> <em><a href="#yrAggregateFunctions">aggreate functions</a> and the <a href="#yrGroupBy">GROUP BY clause</a></em></p>
<section id="example-of-incorrect-select-that-includes-both-aggregate-and-non-aggregated-columns" class="level3" data-number="30.20.1">
<h3 data-number="30.20.1" class="anchored" data-anchor-id="example-of-incorrect-select-that-includes-both-aggregate-and-non-aggregated-columns"><span class="header-section-number">30.20.1</span> Example of INCORRECT select that includes both aggregate and non-aggregated columns</h3>
<!--
Do ***NOT*** do the following. You will *not* get an error, but
***the output WILL BE MISLEADING.*** -->
<!-- YR-TODO fix the hardcoded data for USA, other regions below with
queries to get the right data -->
<p>Examine the query shown below. The SELECT <strong><em>incorrectly</em></strong> uses the aggregate functions <strong><em>avg</em></strong> and <strong><em>max</em></strong> mixed together with non-aggregate data, i.e.&nbsp;<strong><em>region</em></strong> (Note that the region column is NOT part of the GROUP BY). The results are <strong><em>misleading</em></strong>.</p>
<p>Even though the underlying data in the sales table contains Managers for all of the regions (africa, asia, europe, usa), the results below seem to imply that the data in the “Manager” row is only for Managers for the “usa” region. However, that is NOT the case. The <strong><em>maxBase</em></strong> and <strong><em>avgYears</em></strong> columns show the maxBase and avgYears for <strong><em>ALL</em></strong> managers (not just for those from the usa region). The fact that the output shows “usa” and not “africa”, “asia” or “europe” is by chance. There is no guarantee that one of the other regions would be shown in similar queries.</p>
<blockquote class="blockquote">
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">: the -- in the command below introduces a comment in SQLite</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"select title,</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="st">              region, -- DO NOT DO THIS - region is NOT in the GROUP BY</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="st">              avg(baseInThousands) as avgBase, </span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="st">              max(baseInThousands) as maxBase, </span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="st">              avg(yearsWithCompany) as avgYears</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="st">       from sales</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="st">       group by title</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="st">       order by title"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            title region avgBase maxBase avgYears
1         Manager    usa    29.0      40 6.166667
2     Salesperson europe    33.3      50 4.900000
3 Sr. Salesperson    usa    33.5      50 4.750000</code></pre>
</div>
</div>
</blockquote>
<!-- YR-TODO - probably remove this
You can see that there are multiple values of region for Manager
rows 
(i.e. 
*africa\, asia\, europe\, europe\, usa\, usa* ).
However the ouptput in the query above only shows one of those regions
(i.e.
usa
)
It appears that the output
only reflects data from the 
usa
region. However, that is NOT
correct. Each row contains is summary info for 
all rows with the specified title, regardless of the region shown in the output.
-->
<!-- YR-TODO - probably remove this
Therefore, 
even though there will be one row in the output that summarizes all of the
rows for the same title (e.g. all of the *salesperson* rows) there might be
multiple different region values for the different underlying *salesperson* 
rows. To see the different values of region for the diffrent salesperson
rows we can run the following query:

::: {.callout-note}
### there are different regions for different Managers

::: {.cell}

```{.r .cell-code}
sqldf("select title, region, first, last
       from sales
       where title = 'Manager'
       order by region")
```

::: {.cell-output .cell-output-stdout}

```
    title region first     last
1 Manager africa Laura    White
2 Manager   asia   Emy Zeitchik
3 Manager europe  Jack   Martin
4 Manager europe   Sam  Lincoln
5 Manager    usa   Joe    Smith
6 Manager    usa  Zeke    Cohen
```


:::
:::

:::

You can see that there are multiple values of region for Manager
rows 
(i.e. 
*africa\, asia\, europe\, europe\, usa\, usa* ).
However the ouptput in the query below only shows one of those regions
(i.e.
usa
)
It appears that the output
only reflects data from the region that is output. However, that is NOT
correct. The output of a particular row actually is summary info for 
all rows with the specified title, regardless of the region.


-->
<hr>
<p>The following has the same problem but for a query that doesn’t contain a GROUP BY. The results shown below seem to imply that the avgBase, maxBase and avgYears columns only take into account rows from the <strong><em>“usa”</em></strong> region. However, that is NOT the case. the avgBase, maxBase and avgYears take into account rows from <strong><em>ALL</em></strong> regions.</p>
<blockquote class="blockquote">
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">: the -- in the command below introduces a comment in SQLite</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"select </span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="st">              region, -- DO NOT DO THIS - region is NOT in the GROUP BY</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="st">              avg(baseInThousands) as avgBase, </span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="st">              max(baseInThousands) as maxBase, </span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="st">              avg(yearsWithCompany) as avgYears</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="st">       from sales</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a><span class="st">       "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  region  avgBase maxBase avgYears
1    usa 32.29167      50 5.166667</code></pre>
</div>
</div>
</blockquote>
</section>
<section id="explanation" class="level3" data-number="30.20.2">
<h3 data-number="30.20.2" class="anchored" data-anchor-id="explanation"><span class="header-section-number">30.20.2</span> Explanation</h3>
<p>If a SELECT clause contains an <a href="#yrAggregateFunctions">aggregate function</a> then one of the following two things happen:</p>
<ul>
<li><p>If there is no GROUP BY, then only one row is returned.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
click for example
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The following SELECT clause includes aggregate functions and there is NO group by. Therefore only one row is returned.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"select avg(baseInThousands) as avgBase, </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="st">              max(baseInThousands) as maxBase, </span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="st">              avg(yearsWithCompany) as avgYears</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="st">       from sales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   avgBase maxBase avgYears
1 32.29167      50 5.166667</code></pre>
</div>
</div>
</div>
</div>
</div></li>
<li><p>If there IS a GROUP BY then one row is returned per group of rows in the table. (see the <a href="#yrGroupBy">GROUP BY clause</a> above)</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
click for example
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The following statement is very similar to the statement above. However, this statement includes a GROUP BY. Therefore a single row is returned PER GROUP. Note that the SELECT clause also includes the title column, which is also in the GROUP BY clause.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"select title,</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="st">              avg(baseInThousands) as avgBase, </span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="st">              max(baseInThousands) as maxBase, </span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="st">              avg(yearsWithCompany) as avgYears</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="st">       from sales</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="st">       group by title"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            title avgBase maxBase avgYears
1         Manager    29.0      40 6.166667
2     Salesperson    33.3      50 4.900000
3 Sr. Salesperson    33.5      50 4.750000</code></pre>
</div>
</div>
</div>
</div>
</div></li>
</ul>
<p>This makes sense since an aggregate function (e.g.&nbsp;avg, sum, min, max, count) takes multiple values from different rows in the table and returns only a single value. A select statement that doesn’t have a GROUP BY passes the values from all rows in the table to the aggregate function. By contraste, a select with a GROUP BY calls the aggregate functions once for each group of rows.</p>
<p>A SELECT clause that includes aggregated columns as well as<br>
non-aggregated columns is problematic.0 The aggregate function(s) return a single value so only a single row should be diplayed. However, the non-aggregated values could have multiple values and hence multiple rows. This causes a conflict (a) should only one row be returned (because of the aggregate functions) or (b) should more than one row be returned (because of the non-aggregated data)? The rules of SQL say that ONLY ONE ROW is returned. However, ONE OF THE SEVERAL non-aggregated values will also be returned. This could lead to misleading output.</p>
</section>
<section id="ansi-sql-standard-vs-sqlite-vs-other-databases" class="level3" data-number="30.20.3">
<h3 data-number="30.20.3" class="anchored" data-anchor-id="ansi-sql-standard-vs-sqlite-vs-other-databases"><span class="header-section-number">30.20.3</span> ANSI SQL standard vs SQLite vs other databases</h3>
<p>According to the ANSI SQL standard, queries such as those listed above that include both aggregate and non-aggregate columns should cause an ERROR. However, in actuality, different RDBMS software treat this issue differently. By default, when using sqldf() within R, the SQLite version of the SQL is used. SQLite does NOT return an error when issuing such queries. However, as shown above, the results can be very misleading. SQLite’s approach is that the person writing the query is expected to be responsible enough to not break this rule. Other RDBMS software may issue ERRORs or warnings or take a similar approach to SQLite (see the documentation for the specific RDBMS software).</p>
<section id="why-doesnt-sqlite-check-for-this-error" class="level4">
<h4 class="anchored" data-anchor-id="why-doesnt-sqlite-check-for-this-error">Why doesn’t SQLite check for this error?</h4>
<p>There are situations where this rule can be too limiting. For example, the following grades table lists different grades that students got in a class. Each row lists the student’s ID and the student’s social security number (ssn), both of which could theoretically be a primary key for the table (i.e.&nbsp;they are “candiate primary keys”).</p>
<blockquote class="blockquote">
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"select * from grades"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  studentId         ssn assessment grade
1       001 111-11-1111      test1    70
2       001 111-11-1111      test2    80
3       002 222-22-2222      test1    90
4       002 222-22-2222      test2   100</code></pre>
</div>
</div>
</blockquote>
<p>The following query breaks the rule described above (ssn is in the SELECT but not in the GROUP BY). Nevertheless, the query gives accurate results. This is because the studentId and the ssn are guaranteed to each contain the same unique values for a specific student.</p>
<blockquote class="blockquote">
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"select studentId, ssn, avg(grade)</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="st">       from grades</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="st">       group by studentId</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="st">       order by studentId"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  studentId         ssn avg(grade)
1       001 111-11-1111         75
2       002 222-22-2222         95</code></pre>
</div>
</div>
</blockquote>
<p>Similarly, this also breaks the rule (i.e.&nbsp;studentId is in the SELECT but not in the GROUP BY) but the results are accurate:</p>
<blockquote class="blockquote">
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqldf</span>(<span class="st">"select studentId, ssn, avg(grade)</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="st">       from grades</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="st">       group by ssn</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="st">       order by studentId"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  studentId         ssn avg(grade)
1       001 111-11-1111         75
2       002 222-22-2222         95</code></pre>
</div>
</div>
</blockquote>
<p>Bottom line is that SQLite requires the person who is writing the SQL to do it correctly!</p>
<!--
colnames(sales)

select(.data=sales, first, last, salesInThousands)

filter(.data=sales, salesInThousands < 100)

sales |>
  select(first, last, salesInThousands) |>
  filter(salesInThousands < 100)

sales |>
  filter(salesInThousands < 100) |>
  select(first, last, salesInThousands)

sales |>
  filter(salesInThousands < 100) |>
  select(first, last, salesInThousands) |>
  arrange(salesInThousands)

sales |>
  filter(salesInThousands < 100) |>
  select(first, last, salesInThousands) |>
  arrange(desc(salesInThousands))

# show salespeople in alphabetical order
sales |>
  arrange(last,first)

select(.data = filter(.data=sales, salesInThousands < 100),
         first, last, salesInThousands)

dfSales = as.data.frame(sales)

dfSales

as_tibble(dfSales)


# Show the names, titles and salesInThousands
#
# Arrange the results so that all titles are grouped together
# with the rows of a particular title sort the results in
# descending order based on the salesInThousands so that the better salespeople
# appear earlier in the rows for their title.
#
# Only show salespeople for the usa and europe

sales |>
  select(first, last, title, salesInThousands, region) |>
  arrange(title, desc(salesInThousands)) |>
  filter(region %in% c("usa", "europe"))

# Careful - if you take out region, it won't work

sales |>
  select(first, last, title, salesInThousands) |>
  arrange(title, desc(salesInThousands)) |>
  filter(region %in% c("usa", "europe"))

# Instead - rearrange the order of the function calls

sales |>
  arrange(title, desc(salesInThousands)) |>
  filter(region %in% c("usa", "europe")) |>
  select(first, last, title, salesInThousands)

# Use the mutate function to add new columns (can be based on existing data)

# assume that all salespeople get a commission equal to 10% of their sales.
# Create a new column with the name commission that shows the value of their commission
# Create another column called takeHome which has their total takehome pay

sales |>
  mutate(commission=0.10*salesInThousands, takeHome=baseInThousands + 0.10*salesInThousands )

sales |>
  mutate(commission=0.10*salesInThousands) |>
  mutate(takeHome=baseInThousands + commission)


sales |>
  mutate(commission=0.10*salesInThousands, .before=1) |>
  mutate(takeHome=baseInThousands + commission, .before=2)


sales |>
  arrange(title, region)

sales |>
  select (first, last, ends_with("Thousands"))

# group_by and summarize

sales |>
  summarize(mean(salesInThousands))


sales |>
  summarize(mean(salesInThousands), max(salesInThousands), mean(baseInThousands), max(baseInThousands))


sales |>
  summarize(meanSales=mean(salesInThousands),
            maxSales=max(salesInThousands),
            meanBase=mean(baseInThousands),
            maxBase=max(baseInThousands))



-->


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./sql0006-introToDatabases-v023.html" class="pagination-link" aria-label="<yrChapterNumber>29. </yrChapterNumber>  &quot;databases&quot; and &quot;database management systems&quot;">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title"><yrchapternumber>29. </yrchapternumber> “databases” and “database management systems”</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./sql0010-introToSql-v023.html" class="pagination-link" aria-label="<yrChapterNumber>31. </yrChapterNumber> Intro to Relational Databases and SQL ***(no dplyr required)***">
        <span class="nav-page-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title"><yrchapternumber>31. </yrchapternumber> Intro to Relational Databases and SQL <strong><em>(no dplyr required)</em></strong></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>
const titles = document.querySelectorAll('.title');

titles.forEach(title => {
  if (title.textContent.trim().startsWith('Appendix')) {
    const chapterNumber = title.querySelector('yrChapterNumber');
    if (chapterNumber) {
      chapterNumber.classList.add('yrAppendixChapterNumber');
    }
  }
});
</script>




</body></html>